# Generated by Django 6.0.3 on 2026-03-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Biografía'),
        ),
    ]
